### ISSUE TITLE
does not provide attribute 'packages.aarch64-darwin.[hostname]

### ISSUE THREAD

**Issue by ldnsh** [yuanw/nix-home#27]
Hi Yuan, 

Have been trying to install your configuration on to a new MacOs system, though:

```bash
error: flake 'git+file:///Users/ldnsh/Code/nix-home' does not provide attribute 'packages.aarch64-darwin.ldnsh-mac', 'legacyPackages.aarch64-darwin.ldnsh-mac' or 'ldnsh-mac'
```

This is after running the build command `nix build .#ldnsh-mac`

**Comment by yuanw** [comment]
hey ldnsh, 
thank you reaching, you need to change the system at https://github.com/yuanw/nix-home/blob/main/flake.nix#L69 to aarch64-darwin, let me know if that does work
